version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: attendance_mysql
    restart: always
    environment:
      MYSQL_DATABASE: attendance_db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: attendance_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:rootpassword@database:3306/attendance_db
      - SECRET_KEY=37a1f592a34fcbe9b0b46ad88133544c9b91fb8be338d38101a2f1abef6a12d1
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - REFRESH_TOKEN_EXPIRE_DAYS=14
    volumes:
      - ./backend:/app
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app_network

volumes:
  mysql_dev_data:

networks:
  app_network:
    driver: bridge
