<?php
$layout    = 'app';
$pageTitle = 'Generated Documents History';
$breadcrumbs = [['label' => 'Dashboard', 'url' => '/dashboard'], ['label' => 'Documents Workspace', 'url' => '/documents'], ['label' => 'Generated Archives']];
ob_start();
?>

<div class="space-y-6 max-w-6xl mx-auto py-2">

    <!-- Title & Navigation tabs -->
    <div class="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-200 dark:border-slate-800 pb-2">
        <div>
            <h2 class="text-xl font-bold text-slate-900 dark:text-white">Generated Archives</h2>
            <p class="text-xs text-slate-500 mt-0.5">Historical log of all certificates, ID cards, receipts, and report cards generated by the ERP.</p>
        </div>
    </div>

    <!-- Tabs header -->
    <div class="flex items-center gap-6 border-b border-slate-200 dark:border-slate-800">
        <a href="?category=certificates" 
           class="py-3 font-semibold text-xs transition-all <?= $category === 'certificates' ? 'border-b-2 border-indigo-500 text-indigo-600 dark:text-indigo-400' : 'text-slate-400 hover:text-slate-200' ?>">
            📄 Certificates
        </a>
        <a href="?category=student_ids" 
           class="py-3 font-semibold text-xs transition-all <?= $category === 'student_ids' ? 'border-b-2 border-indigo-500 text-indigo-600 dark:text-indigo-400' : 'text-slate-400 hover:text-slate-200' ?>">
            🆔 Student ID Cards
        </a>
    </div>

    <!-- Table -->
    <div class="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900/30 overflow-hidden">
        <table class="w-full text-left border-collapse">
            <thead>
                <tr class="bg-slate-50 dark:bg-slate-900/40 border-b border-slate-200 dark:border-slate-800 text-[10px] font-bold text-slate-400 uppercase tracking-wider">
                    <th class="px-5 py-3">Document Name</th>
                    <th class="px-5 py-3">Student / Staff</th>
                    <th class="px-5 py-3">Generated Date</th>
                    <th class="px-5 py-3">Version</th>
                    <th class="px-5 py-3 text-right">Actions</th>
                </tr>
            </thead>
            <tbody class="divide-y divide-slate-200 dark:divide-slate-850 text-xs">
                <?php if (empty($records)): ?>
                <tr>
                    <td colspan="5" class="px-5 py-8 text-center text-slate-500 dark:text-slate-400">
                        No records found for the selected category.
                    </td>
                </tr>
                <?php else: ?>
                    <?php foreach ($records as $row): ?>
                    <tr class="hover:bg-slate-50/50 dark:hover:bg-slate-850/20 transition-all">
                        <td class="px-5 py-4 font-bold text-slate-800 dark:text-slate-200">
                            <?= e($row['doc_name']) ?>
                        </td>
                        <td class="px-5 py-4">
                            <?= e($row['first_name'] . ' ' . $row['last_name']) ?>
                        </td>
                        <td class="px-5 py-4 whitespace-nowrap text-slate-500 font-mono text-[10px]">
                            <?= date('d M Y, H:i', strtotime($row['created_at'])) ?>
                        </td>
                        <td class="px-5 py-4 whitespace-nowrap text-slate-400">
                            v1.0
                        </td>
                        <td class="px-5 py-4 whitespace-nowrap text-right">
                            <div class="flex items-center justify-end gap-2">
                                <a href="#" onclick="alert('Document is loaded from secure archive.'); return false;" 
                                   class="px-2.5 py-1 rounded bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 font-bold text-[10px] text-slate-700 dark:text-slate-300">
                                    Download
                                </a>
                                <a href="#" onclick="window.print(); return false;" 
                                   class="px-2.5 py-1 rounded bg-indigo-650 hover:bg-indigo-600 font-bold text-[10px] text-white">
                                    Print
                                </a>
                            </div>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
            </tbody>
        </table>
    </div>

</div>

<?php
$content = ob_get_clean();
?>
