<?php $layout = 'parent'; ?>

<div class="space-y-6">

    <!-- Header Panel -->
    <div class="p-5 rounded-2xl border bg-white dark:bg-slate-900/30 border-slate-200 dark:border-white/5 shadow-sm">
        <h3 class="text-base font-bold text-slate-800 dark:text-white">Achievements & Certificates</h3>
        <p class="text-xs text-slate-500 dark:text-slate-400">View and print all official award credentials, achievement programs, and participation certificates issued for <?= e($active_student['first_name'] . ' ' . $active_student['last_name']) ?>.</p>
    </div>

    <!-- Certificates Grid -->
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <?php if (empty($certificates)): ?>
            <div class="col-span-full p-12 rounded-2xl border border-dashed border-slate-200 dark:border-white/5 bg-white dark:bg-slate-900/20 text-center text-slate-500">
                <div class="w-12 h-12 rounded-full bg-slate-100 dark:bg-slate-800 flex items-center justify-center mx-auto mb-3">
                    <svg class="w-6 h-6 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
                </div>
                <p class="text-sm font-semibold">No certificates issued yet.</p>
                <p class="text-xs text-slate-400 mt-1">Official credentials will appear here once generated by school administrators.</p>
            </div>
        <?php else: ?>
            <?php foreach ($certificates as $cert): ?>
                <div class="rounded-2xl border border-slate-200 dark:border-white/5 bg-white dark:bg-slate-900/20 p-6 space-y-4 shadow-sm hover:shadow-md transition-all">
                    <div class="space-y-1">
                        <span class="inline-block px-2.5 py-1 text-[10px] font-bold text-indigo-600 dark:text-indigo-400 bg-indigo-50 dark:bg-indigo-950/40 rounded-full uppercase tracking-wider">
                            <?= e($cert['certificate_type']) ?> Category
                        </span>
                        <h4 class="text-sm font-bold text-slate-800 dark:text-white leading-snug mt-2">
                            <?= e($cert['title']) ?>
                        </h4>
                        <p class="text-xs text-slate-500">
                            Issued: <?= date('d M Y', strtotime($cert['issued_at'])) ?>
                        </p>
                    </div>

                    <div class="pt-3 border-t border-slate-100 dark:border-slate-800/40 flex gap-3 w-full">
                        <a href="/psnf/certificate_generator/index.php?page=download-file&participant_id=<?= (int)$cert['participant_id'] ?>&format=jpg"
                           class="flex-1 text-center py-2.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 dark:bg-slate-800 dark:hover:bg-slate-750 text-xs font-bold text-slate-800 dark:text-white border border-slate-200 dark:border-slate-750 hover:border-slate-650 transition-all shadow-sm">
                            JPG
                        </a>
                        <a href="/psnf/certificate_generator/index.php?page=download-file&participant_id=<?= (int)$cert['participant_id'] ?>&format=pdf"
                           class="flex-1 text-center py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold transition-all shadow-sm">
                            PDF
                        </a>
                    </div>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>

</div>
