# A generic, single-database configuration.

[alembic]
script_location = migrations
prepend_sys_path = .
version_locations = %(here)s/migrations/versions

# We use the DATABASE_URL environment configuration instead of a hardcoded URL.
sqlalchemy.url = mysql+pymysql://root:rootpassword@localhost:3306/attendance_db

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s [%(levelname)s] %(name)s - %(message)s
datefmt = %H:%M:%S
